import Link from "next/link";

export default function HomePage() {
  return (
    <>
      <section style={{ padding: "5.5rem 0 3rem", textAlign: "center", position: "relative" }}>
        <div className="container">
          <div style={{ maxWidth: 960, margin: "0 auto" }}>
            <div style={{
              display: "inline-flex", alignItems: "center", gap: ".45rem",
              background: "var(--accent-bg)", color: "var(--accent)",
              border: "1px solid var(--accent-line)", fontSize: ".78rem",
              fontWeight: 600, padding: ".38rem .85rem", borderRadius: 100,
              marginBottom: "1.6rem"
            }}>
              <span style={{ width: 6, height: 6, background: "var(--accent)", borderRadius: "50%", boxShadow: "0 0 8px var(--accent)" }} />
              AI-powered credit analysis for 22,400+ municipal issuers
            </div>

            <h1 style={{
              fontFamily: "var(--sans)", fontSize: "clamp(1.4rem, 2.2vw, 1.8rem)",
              fontWeight: 700, textTransform: "uppercase", letterSpacing: ".18em",
              color: "var(--text)", marginBottom: ".8rem",
            }}>
              Municipal Credit Analysis Reports
            </h1>

            <h2 style={{
              fontFamily: "var(--sans)", fontSize: "clamp(2.2rem,5vw,4rem)",
              fontWeight: 800, letterSpacing: "-.04em", lineHeight: .95,
              marginBottom: "1.5rem", color: "var(--text)",
            }}>
              Make{" "}
              <span style={{
                fontFamily: "var(--serif)", fontStyle: "italic", fontWeight: 400,
                background: "linear-gradient(135deg, var(--accent) 0%, #7c3aed 50%, #059669 100%)",
                WebkitBackgroundClip: "text", backgroundClip: "text",
                WebkitTextFillColor: "transparent",
              }}>informed decisions.</span>
            </h2>

            <p style={{
              fontSize: "1.15rem", color: "var(--text2)", maxWidth: "58ch",
              margin: "0 auto 2.5rem", lineHeight: 1.6
            }}>
              Search any issuer. Upload financial statements. Get a complete AI-powered credit report with
              five-year analysis, forward projections, and risk flags — <strong style={{ color: "var(--text)" }}>completely free.</strong>
            </p>

            <div style={{ display: "flex", gap: ".7rem", justifyContent: "center", flexWrap: "wrap", marginBottom: ".8rem" }}>
              <Link href="/builder" className="btn btn-accent btn-lg">Start analyzing — it&apos;s free →</Link>
              <Link href="/pricing" className="btn btn-out btn-lg">See plans</Link>
            </div>

            <p style={{ fontSize: ".82rem", color: "var(--text3)", marginTop: "1.2rem" }}>
              <strong style={{ color: "var(--text2)" }}>100% free to use.</strong> No account required.
              1.3M bonds · 22,400 issuers · Create an account to save your reports.
            </p>
          </div>

          {/* Stats row */}
          <div style={{
            display: "grid", gridTemplateColumns: "repeat(4,1fr)",
            borderTop: "1px solid var(--line)", borderBottom: "1px solid var(--line)",
            margin: "3rem 0 0",
          }}>
            {[
              ["1.3M", "Bonds Indexed"],
              ["22.4K", "Issuers"],
              ["< 5 min", "Report Generation"],
              ["50", "States Covered"],
            ].map(([num, label]) => (
              <div key={label} style={{
                padding: "1.8rem 1.2rem", textAlign: "center",
                borderRight: "1px solid var(--line)", position: "relative",
              }}>
                <div style={{
                  position: "absolute", top: 0, left: "50%", transform: "translateX(-50%)",
                  width: 30, height: 2,
                  background: "var(--accent)",
                }} />
                <div style={{
                  fontSize: "2.4rem", fontWeight: 700, letterSpacing: "-.03em", lineHeight: 1, marginBottom: ".3rem",
                  color: "var(--text)",
                }}>{num}</div>
                <div style={{ fontFamily: "var(--mono)", fontSize: ".72rem", color: "var(--text3)", textTransform: "uppercase", letterSpacing: ".1em" }}>{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="block">
        <div className="container">
          <div className="block-head">
            <div className="block-eyebrow">How it works</div>
            <h2>Upload. Analyze. <em>Report.</em></h2>
            <p>Three steps from raw PDFs to a structured credit report with citations, charts, and risk flags — generated by AI, grounded in your documents.</p>
          </div>

          {/* Feature 1: Search */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "3.5rem", alignItems: "center", marginBottom: "5rem" }}>
            <div>
              <div style={{ fontSize: ".78rem", color: "var(--accent)", fontWeight: 600, textTransform: "uppercase", letterSpacing: ".1em", marginBottom: ".7rem" }}>Step 1: Search or Upload</div>
              <h3 style={{ fontSize: "1.9rem", fontWeight: 700, letterSpacing: "-.02em", lineHeight: 1.1, marginBottom: ".9rem" }}>Find any issuer — or drag, drop, and let AI <em style={{ fontFamily: "var(--serif)", fontStyle: "italic", fontWeight: 400 }}>read everything.</em></h3>
              <p style={{ fontSize: "1rem", color: "var(--text2)", lineHeight: 1.6, marginBottom: ".9rem" }}>Type an issuer name and MuniReports searches EMMA, state comptroller sites, and the issuer&apos;s own website. Or upload your own files directly.</p>
              <ul style={{ listStyle: "none", margin: "1rem 0 1.5rem" }}>
                {["Search 22,400 issuers — auto-discovers documents", "Pulls from EMMA, state archives, city websites", "Drag-and-drop your own PDFs, XLSX, CSV", "Auto-detects document type & extracts tables"].map(item => (
                  <li key={item} style={{ padding: ".4rem 0", fontSize: ".94rem", color: "var(--text2)", display: "flex", gap: ".6rem" }}>
                    <span style={{ color: "var(--accent)", fontWeight: 600 }}>✓</span> {item}
                  </li>
                ))}
              </ul>
              <Link href="/builder" className="btn btn-out">Try it now →</Link>
            </div>
            {/* Demo: Search mockup */}
            <div style={{ background: "var(--panel)", border: "1px solid var(--line)", borderRadius: "var(--radius-lg)", padding: "1.4rem", boxShadow: "var(--card-shadow)" }}>
              <div style={{ background: "var(--bg2)", border: "1px solid var(--line)", borderRadius: 10, padding: ".7rem .9rem", marginBottom: "1rem", display: "flex", alignItems: "center", gap: ".5rem" }}>
                <span style={{ fontSize: "1rem" }}>🔎</span>
                <span style={{ color: "var(--text2)", fontSize: ".92rem" }}>City of Austin, TX</span>
              </div>
              {[
                { name: "City of Austin", meta: "City · Travis · TX · Pop. 978,908", rating: "AAA", color: "var(--accent)" },
                { name: "Austin ISD", meta: "School District · Travis · TX · Enrollment 73,200", rating: "AA+", color: "#7c3aed" },
                { name: "Austin Water Utility", meta: "Utility · Travis · TX", rating: "AA+", color: "#059669" },
              ].map((r, i) => (
                <div key={i} style={{ display: "flex", alignItems: "center", gap: ".6rem", padding: ".65rem .7rem", borderBottom: i < 2 ? "1px solid var(--line)" : "none" }}>
                  <div style={{ width: 30, height: 30, borderRadius: 6, background: "var(--accent-bg)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--mono)", fontWeight: 700, color: r.color, fontSize: ".65rem" }}>
                    {r.name.split(" ").filter(w => w.length > 2 && w !== "of").slice(0, 2).map(w => w[0]).join("")}
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontWeight: 600, fontSize: ".85rem" }}>{r.name}</div>
                    <div style={{ fontFamily: "var(--mono)", fontSize: ".68rem", color: "var(--text3)" }}>{r.meta}</div>
                  </div>
                  <div style={{ fontFamily: "var(--mono)", fontSize: ".78rem", fontWeight: 700 }}>{r.rating}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Feature 2: Analysis with chart */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "3.5rem", alignItems: "center", marginBottom: "5rem" }}>
            {/* Demo: Financial chart mockup */}
            <div style={{ background: "var(--panel)", border: "1px solid var(--line)", borderRadius: "var(--radius-lg)", padding: "1.4rem", boxShadow: "var(--card-shadow)" }}>
              <div style={{ fontSize: ".85rem", fontWeight: 600, marginBottom: ".2rem" }}>Revenue vs. Expenditures</div>
              <div style={{ fontFamily: "var(--mono)", fontSize: ".7rem", color: "var(--text3)", marginBottom: "1rem" }}>City of Austin · FY2020 – FY2025 · $M</div>
              {/* SVG bar chart */}
              <svg viewBox="0 0 400 200" style={{ width: "100%", height: "auto" }}>
                {/* Grid lines */}
                {[0, 1, 2, 3, 4].map(i => (
                  <line key={i} x1="40" y1={30 + i * 40} x2="390" y2={30 + i * 40} stroke="var(--line)" strokeWidth="0.5" />
                ))}
                {/* Y-axis labels */}
                <text x="35" y="34" fill="var(--text3)" fontSize="8" textAnchor="end" fontFamily="var(--mono)">$5B</text>
                <text x="35" y="74" fill="var(--text3)" fontSize="8" textAnchor="end" fontFamily="var(--mono)">$4B</text>
                <text x="35" y="114" fill="var(--text3)" fontSize="8" textAnchor="end" fontFamily="var(--mono)">$3B</text>
                <text x="35" y="154" fill="var(--text3)" fontSize="8" textAnchor="end" fontFamily="var(--mono)">$2B</text>
                {/* Revenue bars */}
                {[
                  { x: 55, h: 100, label: "FY20" },
                  { x: 115, h: 112, label: "FY21" },
                  { x: 175, h: 125, label: "FY22" },
                  { x: 235, h: 132, label: "FY23" },
                  { x: 295, h: 140, label: "FY24" },
                  { x: 355, h: 148, label: "FY25" },
                ].map((bar, i) => (
                  <g key={i}>
                    <rect x={bar.x} y={170 - bar.h} width="16" height={bar.h} fill="var(--accent)" rx="2" opacity="0.9" />
                    <rect x={bar.x + 20} y={170 - bar.h + 8} width="16" height={bar.h - 8} fill="#7c3aed" rx="2" opacity="0.7" />
                    <text x={bar.x + 18} y="185" fill="var(--text3)" fontSize="7" textAnchor="middle" fontFamily="var(--mono)">{bar.label}</text>
                  </g>
                ))}
                {/* Legend */}
                <rect x="50" y="195" width="8" height="4" fill="var(--accent)" rx="1" />
                <text x="62" y="199" fill="var(--text2)" fontSize="7" fontFamily="var(--mono)">Revenue</text>
                <rect x="110" y="195" width="8" height="4" fill="#7c3aed" rx="1" />
                <text x="122" y="199" fill="var(--text2)" fontSize="7" fontFamily="var(--mono)">Expenditures</text>
              </svg>
              {/* KPI row */}
              <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: ".5rem", marginTop: ".8rem", paddingTop: ".8rem", borderTop: "1px solid var(--line)" }}>
                <div style={{ textAlign: "center" }}>
                  <div style={{ fontFamily: "var(--mono)", fontSize: ".64rem", color: "var(--text3)", textTransform: "uppercase" }}>5Y CAGR</div>
                  <div style={{ fontWeight: 700, fontSize: "1rem", color: "var(--good)" }}>+6.8%</div>
                </div>
                <div style={{ textAlign: "center" }}>
                  <div style={{ fontFamily: "var(--mono)", fontSize: ".64rem", color: "var(--text3)", textTransform: "uppercase" }}>Op. Margin</div>
                  <div style={{ fontWeight: 700, fontSize: "1rem" }}>4.3%</div>
                </div>
                <div style={{ textAlign: "center" }}>
                  <div style={{ fontFamily: "var(--mono)", fontSize: ".64rem", color: "var(--text3)", textTransform: "uppercase" }}>Fund Bal.</div>
                  <div style={{ fontWeight: 700, fontSize: "1rem" }}>18.4%</div>
                </div>
              </div>
            </div>
            <div>
              <div style={{ fontSize: ".78rem", color: "var(--accent)", fontWeight: 600, textTransform: "uppercase", letterSpacing: ".1em", marginBottom: ".7rem" }}>Step 2: AI Analysis</div>
              <h3 style={{ fontSize: "1.9rem", fontWeight: 700, letterSpacing: "-.02em", lineHeight: 1.1, marginBottom: ".9rem" }}>Five-year history. Forward projections. <em style={{ fontFamily: "var(--serif)", fontStyle: "italic", fontWeight: 400 }}>Risk flags.</em></h3>
              <p style={{ fontSize: "1rem", color: "var(--text2)", lineHeight: 1.6, marginBottom: ".9rem" }}>Once documents are parsed, MuniReports builds a complete financial picture: standardized 5-year statements, three-scenario forecast, CIP analysis, and a five-pillar credit sentiment score.</p>
              <ul style={{ listStyle: "none", margin: "1rem 0 1.5rem" }}>
                {["5-year revenue, expenditure & fund balance trends", "3-scenario forecast (baseline, optimistic, cautious)", "Capital plan with project roster & funding sources", "Sensitivity analysis on key inputs"].map(item => (
                  <li key={item} style={{ padding: ".4rem 0", fontSize: ".94rem", color: "var(--text2)", display: "flex", gap: ".6rem" }}>
                    <span style={{ color: "var(--accent)", fontWeight: 600 }}>✓</span> {item}
                  </li>
                ))}
              </ul>
              <Link href="/builder" className="btn btn-out">Try it now →</Link>
            </div>
          </div>

          {/* Feature 3: Report with sentiment mockup */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "3.5rem", alignItems: "center", marginBottom: "5rem" }}>
            <div>
              <div style={{ fontSize: ".78rem", color: "var(--accent)", fontWeight: 600, textTransform: "uppercase", letterSpacing: ".1em", marginBottom: ".7rem" }}>Step 3: Credit Report</div>
              <h3 style={{ fontSize: "1.9rem", fontWeight: 700, letterSpacing: "-.02em", lineHeight: 1.1, marginBottom: ".9rem" }}>A full credit report. <em style={{ fontFamily: "var(--serif)", fontStyle: "italic", fontWeight: 400 }}>Every claim cited.</em></h3>
              <p style={{ fontSize: "1rem", color: "var(--text2)", lineHeight: 1.6, marginBottom: ".9rem" }}>MuniReports generates a multi-section report: executive summary, financial analysis, capital plan review, debt profile, forward projections, and risk assessment.</p>
              <ul style={{ listStyle: "none", margin: "1rem 0 1.5rem" }}>
                {["12–25 page report with executive summary", "Charts auto-generated from parsed data", "Every claim cites the source document", "Export PDF · Share link · Print-ready"].map(item => (
                  <li key={item} style={{ padding: ".4rem 0", fontSize: ".94rem", color: "var(--text2)", display: "flex", gap: ".6rem" }}>
                    <span style={{ color: "var(--accent)", fontWeight: 600 }}>✓</span> {item}
                  </li>
                ))}
              </ul>
              <Link href="/builder" className="btn btn-accent">Generate a report →</Link>
            </div>
            {/* Demo: Report preview mockup */}
            <div style={{ background: "var(--panel)", border: "1px solid var(--line)", borderRadius: "var(--radius-lg)", padding: "1.4rem", boxShadow: "var(--card-shadow)" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: ".8rem", paddingBottom: ".8rem", borderBottom: "1px solid var(--line)" }}>
                <div>
                  <div style={{ fontWeight: 700, fontSize: ".95rem" }}>City of Austin, TX</div>
                  <div style={{ fontFamily: "var(--mono)", fontSize: ".7rem", color: "var(--text3)" }}>General Obligation · AAA/Aaa</div>
                </div>
                <div style={{ textAlign: "right" }}>
                  <div style={{ fontFamily: "var(--mono)", fontSize: ".64rem", color: "var(--text3)", textTransform: "uppercase" }}>Sentiment</div>
                  <div style={{ fontWeight: 700, color: "var(--good)", fontSize: "1rem" }}>Positive</div>
                  <div style={{ fontFamily: "var(--mono)", fontSize: ".7rem", color: "var(--text3)" }}>Score: 82/100</div>
                </div>
              </div>
              {/* Pillar bars */}
              <div style={{ marginBottom: ".8rem" }}>
                {[
                  { name: "Financial Health", score: 84, color: "var(--good)" },
                  { name: "Revenue Stability", score: 88, color: "var(--good)" },
                  { name: "Debt Profile", score: 76, color: "var(--accent)" },
                  { name: "Liquidity", score: 72, color: "var(--warn)" },
                  { name: "Economic Base", score: 91, color: "var(--good)" },
                ].map((p, i) => (
                  <div key={i} style={{ display: "grid", gridTemplateColumns: "100px 1fr 35px", gap: ".5rem", alignItems: "center", padding: ".35rem 0" }}>
                    <span style={{ fontSize: ".8rem", color: "var(--text2)" }}>{p.name}</span>
                    <div style={{ height: 5, background: "var(--line)", borderRadius: 3, overflow: "hidden" }}>
                      <div style={{ height: "100%", width: `${p.score}%`, background: p.color, borderRadius: 3 }} />
                    </div>
                    <span style={{ fontFamily: "var(--mono)", fontSize: ".78rem", textAlign: "right", fontWeight: 600 }}>{p.score}</span>
                  </div>
                ))}
              </div>
              {/* Risk flags */}
              <div style={{ borderTop: "1px solid var(--line)", paddingTop: ".7rem" }}>
                <div style={{ fontFamily: "var(--mono)", fontSize: ".68rem", color: "var(--text3)", textTransform: "uppercase", letterSpacing: ".06em", marginBottom: ".4rem" }}>Risk Flags</div>
                <div style={{ padding: ".5rem .6rem", background: "var(--warn-bg)", borderLeft: "3px solid var(--warn)", borderRadius: "0 6px 6px 0", marginBottom: ".4rem" }}>
                  <div style={{ fontSize: ".8rem", fontWeight: 600, color: "var(--warn)" }}>⚠️ Rising Pension Obligations</div>
                  <div style={{ fontSize: ".75rem", color: "var(--text2)" }}>TMRS funded ratio declined 2.3% YoY</div>
                </div>
                <div style={{ padding: ".5rem .6rem", background: "var(--bad-bg)", borderLeft: "3px solid var(--bad)", borderRadius: "0 6px 6px 0" }}>
                  <div style={{ fontSize: ".8rem", fontWeight: 600, color: "var(--bad)" }}>🚩 Debt Capacity Pressure</div>
                  <div style={{ fontSize: ".75rem", color: "var(--text2)" }}>CIP adds $1.2B in new issuance through FY2030</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <div className="container">
        <div style={{
          background: "var(--accent)", color: "#fff",
          padding: "5rem 2rem",
          textAlign: "center", borderRadius: 20, maxWidth: 1200, margin: "4rem auto",
          position: "relative", overflow: "hidden"
        }}>
          <div style={{ position: "absolute", top: -200, right: -200, width: 500, height: 500, background: "radial-gradient(circle, rgba(255,255,255,.15) 0%, transparent 70%)", pointerEvents: "none" }} />
          <h2 style={{ fontSize: "clamp(1.9rem,4vw,3.2rem)", fontWeight: 700, letterSpacing: "-.03em", lineHeight: 1.05, marginBottom: "1rem", position: "relative" }}>
            Free credit reports. <em style={{ fontFamily: "var(--serif)", fontStyle: "italic", fontWeight: 400 }}>Right now.</em>
          </h2>
          <p style={{ fontSize: "1.05rem", color: "rgba(255,255,255,.8)", maxWidth: "48ch", margin: "0 auto 2rem", position: "relative" }}>
            No account. No credit card. Search any issuer or upload your docs and have a full credit report in minutes.
          </p>
          <div style={{ display: "flex", gap: ".7rem", justifyContent: "center", flexWrap: "wrap", position: "relative" }}>
            <Link href="/builder" className="btn btn-lg" style={{ background: "#fff", color: "var(--accent)", fontWeight: 700, border: "none" }}>Start analyzing — free →</Link>
            <Link href="/pricing" className="btn btn-out btn-lg" style={{ color: "#fff", borderColor: "rgba(255,255,255,.4)" }}>See plans</Link>
          </div>
        </div>
      </div>
    </>
  );
}
