import Link from "next/link";

export const metadata = {
  title: "Terms of Service — MuniReports",
  description: "MuniReports Terms of Service.",
};

export default function TermsPage() {
  return (
    <main style={{ maxWidth: "780px", margin: "0 auto", padding: "4rem 1.5rem" }}>
      <h1 style={{ fontSize: "2.5rem", marginBottom: "0.5rem" }}>Terms of Service</h1>
      <p style={{ color: "var(--ink-mute)", fontSize: "0.95rem", marginBottom: "2.5rem" }}>
        Last updated: May 5, 2026
      </p>

      <section style={{ marginBottom: "2rem" }}>
        <h2>1. Agreement</h2>
        <p>
          By accessing or using munireports.com (the &quot;Service&quot;), you agree to these Terms of Service. If you do not
          agree, do not use the Service.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>2. The Service</h2>
        <p>
          MuniReports provides AI-assisted credit research briefs for U.S. municipal issuers. Reports are generated using
          large language models combined with public data sources.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>3. NOT A CREDIT RATING AGENCY</h2>
        <p>
          MuniReports is NOT a Nationally Recognized Statistical Rating Organization (NRSRO). The sentiment scores, credit
          assessments, and analysis we provide are research output and DO NOT constitute credit ratings. They should not be
          used as substitutes for ratings issued by Moody&apos;s Investors Service, S&amp;P Global Ratings, Fitch Ratings, KBRA,
          or other registered rating agencies.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>4. NOT INVESTMENT ADVICE</h2>
        <p>
          Reports are for informational and research purposes only. They DO NOT constitute investment, legal, tax, or financial
          advice. Nothing in a report is a recommendation to buy, sell, or hold any security. You are solely responsible for
          your own investment decisions and should consult licensed professionals before acting on any information from the
          Service.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>5. AI-generated content</h2>
        <p>
          Reports are generated by AI and may contain errors, omissions, or outdated information. We make no warranty that
          reports are accurate, complete, or current. You should independently verify any data point before relying on it.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>6. Accounts</h2>
        <p>
          You may use the Service without an account for one free report. Saved reports require a free account. You are
          responsible for maintaining the confidentiality of your account credentials and for all activity under your account.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>7. Payments</h2>
        <p>
          Paid features are billed through Stripe. Reports are sold as one-time purchases ($4.99 single, $19.99 5-pack) or
          via custom unlimited plans. By purchasing, you authorize us to charge your payment method.
        </p>
        <p>
          <strong>Refunds.</strong> If a report fails to generate or is materially defective, contact{" "}
          <a href="mailto:admin@munireports.com">admin@munireports.com</a> within 14 days for a credit or refund. We do not
          offer refunds for reports that generated successfully but did not meet subjective expectations.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>8. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Resell, redistribute, or commercialize MuniReports content without written permission</li>
          <li>Scrape, mass-download, or use automated tools against the Service</li>
          <li>Reverse engineer, copy, or attempt to extract our prompts or models</li>
          <li>Use the Service for any illegal purpose or to violate the rights of others</li>
          <li>Misrepresent reports as official credit ratings or investment advice</li>
        </ul>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>9. Intellectual property</h2>
        <p>
          The Service, its design, codebase, and methodology are owned by MuniReports. Reports you generate are
          licensed for your personal or internal business use. Underlying public data (ACFRs, EMMA disclosures, etc.) belongs
          to its respective issuers and sources.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>10. Disclaimer of warranties</h2>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
          IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT.
          WE DO NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>11. Limitation of liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, MUNIREPORTS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUES, DATA, OR INVESTMENT VALUE, ARISING OUT OF YOUR
          USE OF OR INABILITY TO USE THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO THESE TERMS
          OR THE SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM, OR $100, WHICHEVER IS
          GREATER.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>12. Indemnification</h2>
        <p>
          You agree to indemnify and hold MuniReports harmless from any claims arising out of your misuse of the Service,
          violation of these Terms, or violation of third-party rights.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>13. Termination</h2>
        <p>
          We may suspend or terminate your access at any time for violation of these Terms or other reasons in our sole
          discretion. You may stop using the Service and delete your account at any time.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>14. Governing law</h2>
        <p>
          These Terms are governed by the laws of the State of Texas, without regard to conflict of law principles. Any
          dispute will be resolved in the state or federal courts located in Travis County, Texas.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>15. Changes</h2>
        <p>
          We may modify these Terms from time to time. Material changes will be communicated via email or a notice on the
          Service. Continued use after changes constitutes acceptance.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>16. Contact</h2>
        <p>
          Questions? Email <a href="mailto:admin@munireports.com">admin@munireports.com</a>.
        </p>
      </section>

      <div style={{ marginTop: "3rem" }}>
        <Link href="/" className="btn btn-out">← Back to home</Link>
      </div>
    </main>
  );
}
